plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'com.rule34analyzer'
version = '1.0.0'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = '21.0.6'
    modules = [
            'javafx.controls',
            'javafx.graphics',
            'javafx.fxml'
    ]
}

dependencies {
    implementation 'com.google.code.gson:gson:2.13.2'
}

application {
    mainClass = 'com.rule34analyzer.Bootstrap'
}

shadowJar {
    archiveBaseName.set('Rule34TagAnalyzer')
    archiveClassifier.set('')
    archiveVersion.set(version)

    manifest {
        attributes(
                'Main-Class': application.mainClass.get()
        )
    }
}

tasks.named('build') {
    dependsOn tasks.named('shadowJar')
}
